### ISSUE TITLE
Bias values of the model

### ISSUE THREAD

**Issue by keunwoochoi** [keunwoochoi/Auralisation#1]
```
import h5py
model_name = "vggnet5"
keras_filename = "vggnet5_local_keras_model_CNN_stft_11_frame_173_freq_257_folding_0_best.keras"

f = h5py.File(keras_filename)
```

In `auralise.py`, I only use `param_0`, which is weights. Bias values are in `param_1`

```
>>> f['layer_3']['param_0']
<HDF5 dataset "param_0": shape (64, 64, 3, 3), type "<f4">
>>> f['layer_3']['param_1']
<HDF5 dataset "param_1": shape (64,), type "<f4">
```

**Comment by aseemw** [comment]
Hi Keunwoo,

How have you learned these CNN weights? Which dataset and task have you used? '

Thanks,
Aseem

**Comment by keunwoochoi** [comment]
I used a private dataset, some details are described in the [paper](http://arxiv.org/pdf/1607.02444v1.pdf) - experiment section.
